version: "3.8"

services:
  frontend:
      container_name: balance_frontend
      build:
        context: ./frontend
      volumes:
        - ./frontend:/app
        - /app/node_modules
      environment:
        REACT_APP_BALANCE_API_URL: "http://localhost:4200/api"
      ports:
        - "${FRONTEND_PORT}:${FRONTEND_PORT}"
      working_dir: /app
      command: bash -c "yarn && yarn start"

  balance_api:
    container_name: balance_api
    build:
      context: ./balance-api
      target: ${NODE_ENV}
    volumes:
      - ./balance-api:/app
      - /app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - "9229:9229"
    working_dir: /app
    restart: unless-stopped
    depends_on:
      - balance_db
    command: npm run start:debug
 
  balance_db:
    container_name: balance_db
    image: postgres:14.1
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PG_DATA: /var/lib/postgresql/balance_db
    volumes:
      - db_data:/var/lib/postgresql/balance_db
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped

volumes:
  db_data: {}
