version: "3.8"

services:
  balance_api:
    container_name: balance_api
    build:
      context: .
      target: ${NODE_ENV}
    command: npm run start:debug
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    restart: unless-stopped
    depends_on:
      - balance_db
 
  balance_db:
    container_name: balance_db
    image: postgres:13.3
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - db_data:/var/lib/postgresql/data
      - ${MULTER_DEST}:/var/tmp/uploads
    ports:
      - ${POSTGRES_PORT}:5432
    restart: unless-stopped

volumes:
  db_data: